[toolchain]
anchor_version = "0.29.0"

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_game_manager = "J9TWXt5regfvpX9RSuBy7xSD1k8VTpRWMtBoMS7W1esw"

[programs.devnet]
solana_game_manager = "J9TWXt5regfvpX9RSuBy7xSD1k8VTpRWMtBoMS7W1esw"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm tsx tests/solana-game-manager.ts"
